# Advanced SchoolCafe Menu Card Configuration
# This card intelligently displays school menus with weekend/holiday handling

type: vertical-stack
title: 🍽️ School Lunch Menu
cards:
  # Today's Menu
  - type: conditional
    conditions:
      # Only show if it's a weekday (Monday=1 to Friday=5)
      - condition: numeric_state
        entity: sensor.time
        above: 0
        below: 24
      - condition: template
        value_template: >
          {% set today = now().weekday() %}
          {{ today < 5 }}
    card:
      type: entities
      title: >
        📅 Today - {{ now().strftime('%A, %B %d') }}
      entities:
        # Blue Line Today
        - type: conditional
          conditions:
            - condition: state
              entity: sensor.schoolcafe_blue_line_today
              state_not: "unavailable"
          row:
            entity: sensor.schoolcafe_blue_line_today
            name: "🔵 Blue Line"
            icon: mdi:food
            secondary_info: >
              {% set items = state_attr('sensor.schoolcafe_blue_line_today', 'items') %}
              {% if items and items|length > 0 %}
                {{ items[0].calories }} cal • {{ items[0].rating }}⭐
              {% endif %}
        
        # Gold Line Today  
        - type: conditional
          conditions:
            - condition: state
              entity: sensor.schoolcafe_gold_line_today
              state_not: "unavailable"
          row:
            entity: sensor.schoolcafe_gold_line_today
            name: "🟡 Gold Line"
            icon: mdi:food
            secondary_info: >
              {% set items = state_attr('sensor.schoolcafe_gold_line_today', 'items') %}
              {% if items and items|length > 0 %}
                {{ items[0].calories }} cal • {{ items[0].rating }}⭐
              {% endif %}

        # No School message when no menu available
        - type: conditional
          conditions:
            - condition: template
              value_template: >
                {{ states('sensor.schoolcafe_blue_line_today') == 'No items available' and 
                   states('sensor.schoolcafe_gold_line_today') == 'No items available' }}
          row:
            type: section
            label: "🏫 No School Today"

  # Tomorrow's Menu (if weekday)
  - type: conditional
    conditions:
      - condition: template
        value_template: >
          {% set tomorrow = (now() + timedelta(days=1)).weekday() %}
          {{ tomorrow < 5 }}
    card:
      type: entities
      title: >
        📅 Tomorrow - {{ (now() + timedelta(days=1)).strftime('%A, %B %d') }}
      entities:
        # Blue Line Tomorrow
        - type: conditional
          conditions:
            - condition: state
              entity: sensor.schoolcafe_blue_line_tomorrow
              state_not: "unavailable"
          row:
            entity: sensor.schoolcafe_blue_line_tomorrow
            name: "🔵 Blue Line"
            icon: mdi:food
            secondary_info: >
              {% set items = state_attr('sensor.schoolcafe_blue_line_tomorrow', 'items') %}
              {% if items and items|length > 0 %}
                {{ items[0].calories }} cal • {{ items[0].rating }}⭐
              {% endif %}
        
        # Gold Line Tomorrow
        - type: conditional
          conditions:
            - condition: state
              entity: sensor.schoolcafe_gold_line_tomorrow
              state_not: "unavailable"
          row:
            entity: sensor.schoolcafe_gold_line_tomorrow
            name: "🟡 Gold Line"
            icon: mdi:food
            secondary_info: >
              {% set items = state_attr('sensor.schoolcafe_gold_line_tomorrow', 'items') %}
              {% if items and items|length > 0 %}
                {{ items[0].calories }} cal • {{ items[0].rating }}⭐
              {% endif %}

        # No School message for tomorrow if no menu
        - type: conditional
          conditions:
            - condition: template
              value_template: >
                {{ states('sensor.schoolcafe_blue_line_tomorrow') == 'No items available' and 
                   states('sensor.schoolcafe_gold_line_tomorrow') == 'No items available' }}
          row:
            type: section
            label: "🏫 No School Tomorrow"

  # This Week Overview (Compact view of remaining weekdays)
  - type: entities
    title: "📋 This Week Overview"
    entities:
      # Day 2 (if weekday)
      - type: conditional
        conditions:
          - condition: template
            value_template: >
              {% set day2 = (now() + timedelta(days=2)).weekday() %}
              {{ day2 < 5 }}
        row:
          entity: sensor.schoolcafe_blue_line_day_2
          name: >
            {{ (now() + timedelta(days=2)).strftime('%A') }} - Blue Line
          icon: mdi:calendar-clock
          secondary_info: >
            {% if states('sensor.schoolcafe_blue_line_day_2') != 'No items available' %}
              Menu Available
            {% else %}
              No School
            {% endif %}

      # Day 3 (if weekday)  
      - type: conditional
        conditions:
          - condition: template
            value_template: >
              {% set day3 = (now() + timedelta(days=3)).weekday() %}
              {{ day3 < 5 }}
        row:
          entity: sensor.schoolcafe_blue_line_day_3
          name: >
            {{ (now() + timedelta(days=3)).strftime('%A') }} - Blue Line
          icon: mdi:calendar-clock
          secondary_info: >
            {% if states('sensor.schoolcafe_blue_line_day_3') != 'No items available' %}
              Menu Available
            {% else %}
              No School
            {% endif %}

      # Day 4 (if weekday)
      - type: conditional
        conditions:
          - condition: template
            value_template: >
              {% set day4 = (now() + timedelta(days=4)).weekday() %}
              {{ day4 < 5 }}
        row:
          entity: sensor.schoolcafe_blue_line_day_4
          name: >
            {{ (now() + timedelta(days=4)).strftime('%A') }} - Blue Line
          icon: mdi:calendar-clock
          secondary_info: >
            {% if states('sensor.schoolcafe_blue_line_day_4') != 'No items available' %}
              Menu Available
            {% else %}
              No School
            {% endif %}

  # Weekend Message
  - type: conditional
    conditions:
      - condition: template
        value_template: >
          {% set today = now().weekday() %}
          {{ today >= 5 }}
    card:
      type: markdown
      content: |
        ## 🏖️ Weekend - No School
        
        Enjoy your weekend! School menus will be available again on Monday.
        
        Next school day: **{{ (now() + timedelta(days=(7-now().weekday()))).strftime('%A, %B %d') }}**