name: "Validate HACS"

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'custom_components/**'
      - 'hacs.json'
      - '.github/workflows/hacs.yml'

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
          # Ignore brands validation for custom integrations
          ignore: "brands"