name: "Validate HACS"

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
          # Ignore brands validation for custom integrations
          ignore: "brands"