name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          # Remove 'v' prefix if present
          VERSION=${VERSION#v}
          
          # Validate semantic versioning format
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must follow semantic versioning (e.g., 1.0.0)"
            exit 1
          fi
          
          # Update manifest.json with the new version
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" custom_components/schoolcafe/manifest.json
          
          echo "Version $VERSION is valid"

      - name: Create Release Archive
        run: |
          cd custom_components
          zip -r ../schoolcafe.zip schoolcafe/
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./schoolcafe.zip
          asset_name: schoolcafe.zip
          asset_content_type: application/zip